- id: go-fmt
  name: 'go fmt'
  entry: ./scripts/run-go-fmt.sh
  files: '\.go$'
  language: 'script'
  description: "Runs `go fmt`, requires golang"
- id: go-vet
  name: 'go vet'
  entry: ./scripts/run-go-vet.sh
  files: '\.go$'
  language: 'script'
  description: "Runs `go vet`, requires golang"
- id: go-test
  name: 'go test'
  entry: ./scripts/run-go-test.sh
  files: '\.go$'
  language: 'script'
  description: "Runs `go vet`, requires golang"
- id: gometalinter
  name: 'gometalinter'
  entry: ./scripts/run-gometalinter.sh
  files: '\.go$'
  language: 'script'
  description: ""